server:
  port: 8087
  servlet:
    context-path: /
    session:
      timeout: 60s
  tomcat:
    max-threads: 100
    uri-encoding: UTF-8
spring:
  application:
    name: nacos-hystrix
  cloud:
    nacos:
      host: localhost
      port: 8500
      discovery:
        service: ${spring.application.name} # 注册到nacos的服务名称
        server-addr: 127.0.0.1:8848	# nacos ip
turbine:
  instanceUrlSuffix: hystrix.stream    # 指定收集路径
  appConfig: nacos-discovery-client    # 指定了需要收集监控信息的服务名，多个以“,”进行区分
  clusterNameExpression: "'default'"    # 指定集群名称,若为default则为默认集群，多个集群则通过此配置区分
  combine-host-port: true    # 此配置默认为false，则服务是以host进行区分，若设置为true则以host+port进行区分