server:
  port: 9090

spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: elasticsearch
      repositories:
        enabled: true
logging:
  level:
    com:
      pf:
        myelasticsearchone: debug
    org:
      springframework:
        web: info